<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Dashboard-QuickLaunch</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>0a59d3c2-f4e0-40b1-ae66-dd44c9304fcc</testSuiteGuid>
   <testCaseLink>
      <guid>35585de9-1838-432f-af83-77e50f66d157</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/Quick Launch/ApplyLeave</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6bf0aac1-2e92-4a56-8edc-54116c268951</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d0438dfd-fb01-4c8a-955d-4874df6bbaea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/Quick Launch/Click on the Assign Leave</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa741527-5527-4072-a2e1-44bf3c61beeb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>73e4233f-f1dd-4920-b275-cb489ed8084f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/Quick Launch/Click on the Leave List</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6692818-f76a-497d-971a-5636d59ccdcc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c8482855-743d-4399-b1db-4ff5285df574</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/Quick Launch/My TimeSheet</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0941892-2569-42b1-bdd8-a2c4a1af0f72</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>77b1b6ba-2bd7-4938-bc83-81f255f7ee27</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/Quick Launch/MyLeave</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60267564-791a-4da1-823b-15cfc39176ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b8ebc4a2-7dc6-446e-8c72-f61e2064053e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/Quick Launch/Quick Launch elements</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e37da904-72fb-4315-8a8a-9f0727ab27a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/Quick Launch/TimeSheets</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90e7ed0b-9205-4676-85e8-371649d88a25</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
