<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Dashboard-MyActions</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>8543c4f5-a66c-4ac6-9da0-d79c6edb26aa</testSuiteGuid>
   <testCaseLink>
      <guid>1c858feb-a444-4038-adf1-59f1e4b68374</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/My Action/Click on Leave Reaquest to Aprove</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a5ef47a0-6317-4110-bce9-17c050ff38c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d1deb66-e928-4887-9a2a-889436b97759</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/My Action/Click on the Candidate to Interview</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>944f8c4b-a026-4e50-9ce0-226afbfa6be4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05227f76-3b81-48f5-9272-e1c23659297e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/My Action/Click on the Pending Self Review</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d93e37f-ed24-43f1-bd39-0d0ccd85e2f8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4a28d692-47e9-44e9-8ad3-32cbd101029d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/My Action/Click on the Timesheets to Approve</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b1d2b44-03b2-40f4-b623-c799194b4b81</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d717cbb-ec1d-4dc0-8f12-3a6864758771</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Dashboard page/My Action/My Action elements</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
