<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NavigationBar</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7d2b4855-dd11-4c79-b931-706eefabb1bd</testSuiteGuid>
   <testCaseLink>
      <guid>089613f9-c54f-4c93-8420-7b14e341b320</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/AdminLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54ed9c5d-bc4a-4776-acfe-c0bd0e93be7a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05132929-8ff7-4377-8d38-cdd2c3e84464</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/BuzzLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd07a0d-8964-493b-ac6b-941860e49f5b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10ea798a-d686-41e3-8e6d-9cb492c2d2ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/DashboardLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1d4502d-c7e9-4bbf-8b95-c08054e953e4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cface78d-9478-4e24-a717-2ab7e5ec983f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/DirectoryLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b34d46c1-ddff-4590-ab1d-62b9b05c4168</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9abbb812-f70f-4b7a-8d7f-e0c9b954d54e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/LeaveLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>698ad69b-278c-4570-bf6e-f83cabbf2e8f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bed47e5c-e105-4a10-9d1e-7839a8e4329a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/MaintenanceLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd2c4d0c-31a9-412e-83dc-9456f39d7e9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f8257cd-01c2-4724-b831-29275fc76f44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/MyInfoLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e32dacd-d392-4c6e-bd0d-0666846f5619</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fbc7725f-d375-484d-8bf1-8316f6fa6c7e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/NavigationBar Can Expand-Collaps</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b34f0252-7126-41c3-9bd5-a1521a2685be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/NavigationBar ElementsExpanded</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>ab97dd1d-115f-4a87-a943-26c648f656e7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/PerformanceLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e838f15-8fcc-4e32-960f-86a971cb2304</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a3f39c6-4dad-4703-8d93-ac78dca25da5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/PIMLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e1a10e0-71f2-46a1-87a1-7b87cd1d42a9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>397932c5-83a1-43c9-82de-7973292f3aea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/RecuruitmnetLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d3a2a34-25fd-4562-885c-1e3b7914b222</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>277deb85-1dd2-470c-8181-f4e281626e94</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/NavigationBar/TimeLink</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df160876-024d-4579-9296-05b03009a8d8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
