<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Employee NameAaliyah HaqUsernameAaliyah_cd4cd7</name>
   <tag></tag>
   <elementGuidId>953591a0-a6c0-4f88-978a-23c17e8487ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b864dfd8-616e-4f5d-8f56-efbd296edbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>59c8f022-d4f9-4d45-8134-e647242552ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee NameAaliyah HaqUsernameAaliyah.Haq1User RoleESSStatusEnabledEmployee NameElon ColljiingsUsernameAdminUser RoleAdminStatusEnabledEmployee NamePT_User 153Usernameadmin1User RoleAdminStatusEnabledEmployee Nameemployee test1Usernamealex36User RoleAdminStatusEnabledEmployee NameAnthony NolanUsernameAnthony.NolanUser RoleESSStatusEnabledEmployee NameAshlea BartolettiUsernameAshlea1391User RoleESSStatusEnabledEmployee NameCassidy HopeUsernameCassidy.HopeUser RoleESSStatusEnabledEmployee NameCecil BonaparteUsernameCecil.BonaparteUser RoleESSStatusEnabledEmployee NameCharlie CarterUsernameCharlie.CarterUser RoleESSStatusEnabledEmployee NameChenzira ChukiUsernameChenzira.ChukiUser RoleESSStatusEnabledEmployee NameDavid MorrisUsernameDavid.MorrisUser RoleESSStatusEnabledEmployee NameKunal Dangr1UsernameDikshaUser RoleESSStatusEnabledEmployee NameDominic ChaseUsernameDominic.ChaseUser RoleAdminStatusEnabledEmployee NameEhioze EboUsernameEhioze.EboUser RoleESSStatusEnabledEmployee NameFiona GraceUsernameFiona.GraceUser RoleESSStatusEnabledEmployee NameGarry WhiteUsernameGarry.WhiteUser RoleESSStatusEnabledEmployee NameGoutam GaneshUsernameGoutam.GaneshUser RoleESSStatusEnabledEmployee NameJess CrooksUsernameIsuriUser RoleAdminStatusEnabledEmployee NameJacqueline WhiteUsernameJacqueline.WhiteUser RoleESSStatusEnabledEmployee NameJadine JackieUsernameJadine.JackieUser RoleESSStatusEnabledEmployee NameJane DoeUsernamejanedoeUser RoleESSStatusEnabledEmployee NameJasmine MorganUsernameJasmine.MorganUser RoleESSStatusEnabledEmployee NameJoe RootUsernameJoe.RootUser RoleESSStatusEnabledEmployee NameJohn SmithUsernameJohn.SmithUser RoleAdminStatusEnabledEmployee NameJordan MathewsUsernameJordan.MathewsUser RoleESSStatusEnabledEmployee NameKevin MathewsUsernameKevin.MathewsUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernamekiki1234User RoleAdminStatusEnabledEmployee NamePeter AndersonUsernamekisi12345User RoleAdminStatusDisabledEmployee NameKiyara HuUsernameKiyara.HuUser RoleESSStatusEnabledEmployee NameLinda AndersonUsernameLinda.AndersonUser RoleAdminStatusEnabledEmployee NameJess CrooksUsernamelionel.hilllUser RoleESSStatusEnabledEmployee NameLisa AndrewsUsernameLisa.AndrewsUser RoleESSStatusEnabledEmployee NameLuke WrightUsernameLuke.WrightUser RoleESSStatusEnabledEmployee NameMaggie ManningUsernameMaggie.ManningUser RoleESSStatusEnabledEmployee NameAlice DuvalUsernameMaheshUser RoleAdminStatusEnabledEmployee NameMelan PeirisUsernameMelan.PeirisUser RoleESSStatusEnabledEmployee NameNathan ElliotUsernameNathan.ElliotUser RoleESSStatusEnabledEmployee NameNina PatelUsernameNina.PatelUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernameOdis.AdalwinUser RoleAdminStatusEnabledEmployee NameOdis AdalwinUsernameodis123User RoleAdminStatusEnabledEmployee NamePeter AndersonUsernamePeter.AndersonUser RoleAdminStatusEnabledEmployee NameProject ATUsernameProject-AT8User RoleESSStatusEnabledEmployee NamePT_User 711UsernameRaghuUser RoleESSStatusDisabledEmployee NameRebecca HarmonyUsernameRebecca.HarmonyUser RoleESSStatusEnabledEmployee NameRonnie HilpertUsernameRonnie8192User RoleESSStatusEnabledEmployee NameRussel HamiltonUsernameRussel.HamiltonUser RoleESSStatusEnabledEmployee NamePT_User 153UsernamesaikrishnaUser RoleAdminStatusEnabledEmployee NameSania ShaheenUsernameSania.ShaheenUser RoleESSStatusEnabledEmployee NameSara TencradyUsernameSara.TencradyUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernameShubhamUser RoleAdminStatusEnabled</value>
      <webElementGuid>3a89ed39-7187-484a-a9b7-1b11ebf8cc69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>c1d3fddb-6bc7-496b-aa26-57b0a4918986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[3]</value>
      <webElementGuid>89736ff4-8dfd-4be8-8b2c-6ace79d6e758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]</value>
      <webElementGuid>5319a5b4-a141-410a-b0a2-35dffe9e32c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Employee NameAaliyah HaqUsernameAaliyah.Haq1User RoleESSStatusEnabledEmployee NameElon ColljiingsUsernameAdminUser RoleAdminStatusEnabledEmployee NamePT_User 153Usernameadmin1User RoleAdminStatusEnabledEmployee Nameemployee test1Usernamealex36User RoleAdminStatusEnabledEmployee NameAnthony NolanUsernameAnthony.NolanUser RoleESSStatusEnabledEmployee NameAshlea BartolettiUsernameAshlea1391User RoleESSStatusEnabledEmployee NameCassidy HopeUsernameCassidy.HopeUser RoleESSStatusEnabledEmployee NameCecil BonaparteUsernameCecil.BonaparteUser RoleESSStatusEnabledEmployee NameCharlie CarterUsernameCharlie.CarterUser RoleESSStatusEnabledEmployee NameChenzira ChukiUsernameChenzira.ChukiUser RoleESSStatusEnabledEmployee NameDavid MorrisUsernameDavid.MorrisUser RoleESSStatusEnabledEmployee NameKunal Dangr1UsernameDikshaUser RoleESSStatusEnabledEmployee NameDominic ChaseUsernameDominic.ChaseUser RoleAdminStatusEnabledEmployee NameEhioze EboUsernameEhioze.EboUser RoleESSStatusEnabledEmployee NameFiona GraceUsernameFiona.GraceUser RoleESSStatusEnabledEmployee NameGarry WhiteUsernameGarry.WhiteUser RoleESSStatusEnabledEmployee NameGoutam GaneshUsernameGoutam.GaneshUser RoleESSStatusEnabledEmployee NameJess CrooksUsernameIsuriUser RoleAdminStatusEnabledEmployee NameJacqueline WhiteUsernameJacqueline.WhiteUser RoleESSStatusEnabledEmployee NameJadine JackieUsernameJadine.JackieUser RoleESSStatusEnabledEmployee NameJane DoeUsernamejanedoeUser RoleESSStatusEnabledEmployee NameJasmine MorganUsernameJasmine.MorganUser RoleESSStatusEnabledEmployee NameJoe RootUsernameJoe.RootUser RoleESSStatusEnabledEmployee NameJohn SmithUsernameJohn.SmithUser RoleAdminStatusEnabledEmployee NameJordan MathewsUsernameJordan.MathewsUser RoleESSStatusEnabledEmployee NameKevin MathewsUsernameKevin.MathewsUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernamekiki1234User RoleAdminStatusEnabledEmployee NamePeter AndersonUsernamekisi12345User RoleAdminStatusDisabledEmployee NameKiyara HuUsernameKiyara.HuUser RoleESSStatusEnabledEmployee NameLinda AndersonUsernameLinda.AndersonUser RoleAdminStatusEnabledEmployee NameJess CrooksUsernamelionel.hilllUser RoleESSStatusEnabledEmployee NameLisa AndrewsUsernameLisa.AndrewsUser RoleESSStatusEnabledEmployee NameLuke WrightUsernameLuke.WrightUser RoleESSStatusEnabledEmployee NameMaggie ManningUsernameMaggie.ManningUser RoleESSStatusEnabledEmployee NameAlice DuvalUsernameMaheshUser RoleAdminStatusEnabledEmployee NameMelan PeirisUsernameMelan.PeirisUser RoleESSStatusEnabledEmployee NameNathan ElliotUsernameNathan.ElliotUser RoleESSStatusEnabledEmployee NameNina PatelUsernameNina.PatelUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernameOdis.AdalwinUser RoleAdminStatusEnabledEmployee NameOdis AdalwinUsernameodis123User RoleAdminStatusEnabledEmployee NamePeter AndersonUsernamePeter.AndersonUser RoleAdminStatusEnabledEmployee NameProject ATUsernameProject-AT8User RoleESSStatusEnabledEmployee NamePT_User 711UsernameRaghuUser RoleESSStatusDisabledEmployee NameRebecca HarmonyUsernameRebecca.HarmonyUser RoleESSStatusEnabledEmployee NameRonnie HilpertUsernameRonnie8192User RoleESSStatusEnabledEmployee NameRussel HamiltonUsernameRussel.HamiltonUser RoleESSStatusEnabledEmployee NamePT_User 153UsernamesaikrishnaUser RoleAdminStatusEnabledEmployee NameSania ShaheenUsernameSania.ShaheenUser RoleESSStatusEnabledEmployee NameSara TencradyUsernameSara.TencradyUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernameShubhamUser RoleAdminStatusEnabled' or . = 'Employee NameAaliyah HaqUsernameAaliyah.Haq1User RoleESSStatusEnabledEmployee NameElon ColljiingsUsernameAdminUser RoleAdminStatusEnabledEmployee NamePT_User 153Usernameadmin1User RoleAdminStatusEnabledEmployee Nameemployee test1Usernamealex36User RoleAdminStatusEnabledEmployee NameAnthony NolanUsernameAnthony.NolanUser RoleESSStatusEnabledEmployee NameAshlea BartolettiUsernameAshlea1391User RoleESSStatusEnabledEmployee NameCassidy HopeUsernameCassidy.HopeUser RoleESSStatusEnabledEmployee NameCecil BonaparteUsernameCecil.BonaparteUser RoleESSStatusEnabledEmployee NameCharlie CarterUsernameCharlie.CarterUser RoleESSStatusEnabledEmployee NameChenzira ChukiUsernameChenzira.ChukiUser RoleESSStatusEnabledEmployee NameDavid MorrisUsernameDavid.MorrisUser RoleESSStatusEnabledEmployee NameKunal Dangr1UsernameDikshaUser RoleESSStatusEnabledEmployee NameDominic ChaseUsernameDominic.ChaseUser RoleAdminStatusEnabledEmployee NameEhioze EboUsernameEhioze.EboUser RoleESSStatusEnabledEmployee NameFiona GraceUsernameFiona.GraceUser RoleESSStatusEnabledEmployee NameGarry WhiteUsernameGarry.WhiteUser RoleESSStatusEnabledEmployee NameGoutam GaneshUsernameGoutam.GaneshUser RoleESSStatusEnabledEmployee NameJess CrooksUsernameIsuriUser RoleAdminStatusEnabledEmployee NameJacqueline WhiteUsernameJacqueline.WhiteUser RoleESSStatusEnabledEmployee NameJadine JackieUsernameJadine.JackieUser RoleESSStatusEnabledEmployee NameJane DoeUsernamejanedoeUser RoleESSStatusEnabledEmployee NameJasmine MorganUsernameJasmine.MorganUser RoleESSStatusEnabledEmployee NameJoe RootUsernameJoe.RootUser RoleESSStatusEnabledEmployee NameJohn SmithUsernameJohn.SmithUser RoleAdminStatusEnabledEmployee NameJordan MathewsUsernameJordan.MathewsUser RoleESSStatusEnabledEmployee NameKevin MathewsUsernameKevin.MathewsUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernamekiki1234User RoleAdminStatusEnabledEmployee NamePeter AndersonUsernamekisi12345User RoleAdminStatusDisabledEmployee NameKiyara HuUsernameKiyara.HuUser RoleESSStatusEnabledEmployee NameLinda AndersonUsernameLinda.AndersonUser RoleAdminStatusEnabledEmployee NameJess CrooksUsernamelionel.hilllUser RoleESSStatusEnabledEmployee NameLisa AndrewsUsernameLisa.AndrewsUser RoleESSStatusEnabledEmployee NameLuke WrightUsernameLuke.WrightUser RoleESSStatusEnabledEmployee NameMaggie ManningUsernameMaggie.ManningUser RoleESSStatusEnabledEmployee NameAlice DuvalUsernameMaheshUser RoleAdminStatusEnabledEmployee NameMelan PeirisUsernameMelan.PeirisUser RoleESSStatusEnabledEmployee NameNathan ElliotUsernameNathan.ElliotUser RoleESSStatusEnabledEmployee NameNina PatelUsernameNina.PatelUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernameOdis.AdalwinUser RoleAdminStatusEnabledEmployee NameOdis AdalwinUsernameodis123User RoleAdminStatusEnabledEmployee NamePeter AndersonUsernamePeter.AndersonUser RoleAdminStatusEnabledEmployee NameProject ATUsernameProject-AT8User RoleESSStatusEnabledEmployee NamePT_User 711UsernameRaghuUser RoleESSStatusDisabledEmployee NameRebecca HarmonyUsernameRebecca.HarmonyUser RoleESSStatusEnabledEmployee NameRonnie HilpertUsernameRonnie8192User RoleESSStatusEnabledEmployee NameRussel HamiltonUsernameRussel.HamiltonUser RoleESSStatusEnabledEmployee NamePT_User 153UsernamesaikrishnaUser RoleAdminStatusEnabledEmployee NameSania ShaheenUsernameSania.ShaheenUser RoleESSStatusEnabledEmployee NameSara TencradyUsernameSara.TencradyUser RoleESSStatusEnabledEmployee NameOdis AdalwinUsernameShubhamUser RoleAdminStatusEnabled')]</value>
      <webElementGuid>882b7f08-16bf-4844-97fb-645b008eecd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
