<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Unassigned_NXfebeAg</name>
   <tag></tag>
   <elementGuidId>5d6e25b9-fdb0-49c0-a2aa-43fd424ed9b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NXfebeAg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>bc90cc11-0613-4620-800c-c693a825d541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NXfebeAg</value>
      <webElementGuid>ac68646b-b00c-49ff-8517-e1633392497c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>326</value>
      <webElementGuid>0a9803bc-eaed-456a-a943-863d0698b419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>265</value>
      <webElementGuid>77d99e15-39ba-4e41-a06d-aa28ae2fb1ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NXfebeAg&quot;)</value>
      <webElementGuid>ad64b9e4-3036-4143-965d-a4e91f18670f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='NXfebeAg']</value>
      <webElementGuid>ece74247-0428-4a0e-85d5-69c44aa39aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[6]/div/div[2]/div/div/canvas</value>
      <webElementGuid>8ef403bc-899a-41b8-875a-c97c816c2031</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/canvas</value>
      <webElementGuid>921b1553-b393-4d90-a368-d84575ebc51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'NXfebeAg']</value>
      <webElementGuid>3c81f82e-44ba-4d03-8560-8628ca9cabac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
