<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Unassigned_nyu9nIDf</name>
   <tag></tag>
   <elementGuidId>d4a276b6-ec79-4aaa-b236-720d50334e51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nyu9nIDf</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[6]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>9b04f361-8335-43e2-bb9d-51817b2165d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nyu9nIDf</value>
      <webElementGuid>7c5515ee-95af-46ec-8c21-5c8848a2bd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>326</value>
      <webElementGuid>577fbcb0-2c28-4036-8c5c-df95a4355c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>265</value>
      <webElementGuid>375336cd-c895-4b6b-836f-55d5f828725a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nyu9nIDf&quot;)</value>
      <webElementGuid>63739876-18c0-49dd-94b0-72c9abac3b91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='nyu9nIDf']</value>
      <webElementGuid>615669cd-7705-442a-93d6-d220fbd368eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[6]/div/div[2]/div/div/canvas</value>
      <webElementGuid>37296d33-20c4-4bee-aeff-c4a7b746cf2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/canvas</value>
      <webElementGuid>6858453a-1751-4078-b7bf-49e48ddb5410</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'nyu9nIDf']</value>
      <webElementGuid>8d783988-0798-4d54-a62b-fb507a1d0210</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
