<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Today_uk_8H4Fb</name>
   <tag></tag>
   <elementGuidId>aac3ef95-fae5-4210-b6b7-60c9d81c4472</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uk_8H4Fb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;app&quot;]/div[1]/div[2]/div[2]/div/div[5]/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>0167ea09-fca1-4dda-a995-a63056aa3220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uk_8H4Fb</value>
      <webElementGuid>7695bdac-0e57-4b44-9b64-1142e4931eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>318</value>
      <webElementGuid>f72f0f67-2874-455c-9344-e6f434c4f867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>265</value>
      <webElementGuid>59a76dfc-c4f1-4a6f-87d6-5dca29099763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uk_8H4Fb&quot;)</value>
      <webElementGuid>5ffa13fc-094e-457f-86cd-fc8a07955473</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='uk_8H4Fb']</value>
      <webElementGuid>2bea58cc-13f3-4bb8-a625-c936ce1caad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[5]/div/div[2]/div/div/canvas</value>
      <webElementGuid>1b3c3bed-412e-45fe-ad08-4399d0b2fffe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/canvas</value>
      <webElementGuid>5fd23a2a-27fc-4be5-967c-cfd81604dbde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = 'uk_8H4Fb']</value>
      <webElementGuid>dc5ece0e-998d-4288-ad83-34e126660abc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
